/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;

/**
 *
 * @author Cristian
 */
public class VistaVenta extends javax.swing.JFrame {

    /**
     * Creates new form VistaClientes
     */
    public VistaVenta() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog3 = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaProductos2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JTextField();
        btnSalirProductos2 = new javax.swing.JButton();
        btnAgregarProductos = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaMayoristas = new javax.swing.JTable();
        btnAgregarID = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoPaternoRepartidor = new javax.swing.JTextField();
        txtApellidoMaternoRepartidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadGarrafonesSolicitados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdRepartidor = new javax.swing.JTextField();
        txtTelefonoRepartidor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantidadGarrafonesDevueltos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadGarrafonesVendidos = new javax.swing.JTextField();
        cbPrecios = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtCantidadGarrafones = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaRegistroProductosRepartidor = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        btnAgregarVenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCalcularTotalGarrafones = new javax.swing.JButton();
        btnAgregarSubVentas = new javax.swing.JButton();
        btnBuscadorEmpleado = new javax.swing.JButton();
        lblFechaVenta1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtPrecioEspecial = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        txtIdMayorista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBuscadorClientes = new javax.swing.JButton();
        txtCambio = new javax.swing.JTextField();
        btnCalcularTotal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaRegistroProductos = new javax.swing.JTable();
        btnRepartidor = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        txtApellidoPaternoCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(25, 34, 63));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Productos.");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 90));

        tablaProductos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProducto", "Nombre", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaProductos2);

        jPanel9.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 710, 160));

        jLabel16.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel16.setText("Cantidad:");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txtCantidad2.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        txtCantidad2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCantidad2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel9.add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 70, 36));

        btnSalirProductos2.setBackground(new java.awt.Color(25, 34, 63));
        btnSalirProductos2.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        btnSalirProductos2.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirProductos2.setText("Salir.");
        btnSalirProductos2.setBorder(null);
        btnSalirProductos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirProductos2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirProductos2MouseExited(evt);
            }
        });
        btnSalirProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirProductos2ActionPerformed(evt);
            }
        });
        jPanel9.add(btnSalirProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 112, 41));

        btnAgregarProductos.setBackground(new java.awt.Color(25, 34, 63));
        btnAgregarProductos.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        btnAgregarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProductos.setText("Agregar.");
        btnAgregarProductos.setBorder(null);
        btnAgregarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProductosMouseExited(evt);
            }
        });
        btnAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductosActionPerformed(evt);
            }
        });
        jPanel9.add(btnAgregarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 112, 41));

        jDialog3.getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(25, 34, 63));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Clientes.");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 90));

        tablaMayoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdMayorista", "Nombre", "Apellido paterno", "Apellido materno", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tablaMayoristas);

        jPanel11.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 710, 210));

        btnAgregarID.setBackground(new java.awt.Color(25, 34, 63));
        btnAgregarID.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        btnAgregarID.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarID.setText("Agregar ID.");
        btnAgregarID.setBorder(null);
        btnAgregarID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarIDMouseExited(evt);
            }
        });
        btnAgregarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIDActionPerformed(evt);
            }
        });
        jPanel11.add(btnAgregarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 112, 41));

        jDialog1.getContentPane().add(jPanel11, java.awt.BorderLayout.CENTER);

        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        txtNombreEmpleado.setEditable(false);

        txtApellidoPaternoRepartidor.setEditable(false);

        txtApellidoMaternoRepartidor.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Registro de venta para repartidores.");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Datos del repartidor.");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N

        txtIdRepartidor.setToolTipText("");

        txtTelefonoRepartidor.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setText("Datos de la venta.");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("-");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("=");

        txtCantidadGarrafonesVendidos.setEditable(false);
        txtCantidadGarrafonesVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadGarrafonesVendidosActionPerformed(evt);
            }
        });

        cbPrecios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12", "13", "14", "15" }));
        cbPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPreciosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Precio.");

        tablaRegistroProductosRepartidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Precio", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaRegistroProductosRepartidor);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Total.");

        txtTotalVenta.setEditable(false);
        txtTotalVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVentaActionPerformed(evt);
            }
        });

        btnAgregarVenta.setBackground(new java.awt.Color(38, 157, 46));
        btnAgregarVenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnAgregarVenta.setText("Agregar venta.");
        btnAgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVentaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(38, 157, 46));
        btnVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver.");
        btnVolver.setActionCommand("");

        btnCalcularTotalGarrafones.setBackground(new java.awt.Color(38, 157, 46));
        btnCalcularTotalGarrafones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCalcularTotalGarrafones.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularTotalGarrafones.setText("Calcular total de garrafones vendidos.");
        btnCalcularTotalGarrafones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalGarrafonesActionPerformed(evt);
            }
        });

        btnAgregarSubVentas.setBackground(new java.awt.Color(38, 157, 46));
        btnAgregarSubVentas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregarSubVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarSubVentas.setText("+ Agregar subventas.");

        btnBuscadorEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscador1.png"))); // NOI18N
        btnBuscadorEmpleado.setContentAreaFilled(false);
        btnBuscadorEmpleado.setOpaque(true);

        lblFechaVenta1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCantidadGarrafonesSolicitados, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10))
                                            .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txtIdRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBuscadorEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(txtTelefonoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtCantidadGarrafonesDevueltos, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(txtApellidoPaternoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(27, 27, 27)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtApellidoMaternoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCantidadGarrafonesVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(147, 147, 147)
                        .addComponent(lblFechaVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(34, 34, 34)
                                .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularTotalGarrafones))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cbPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txtCantidadGarrafones, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAgregarSubVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblFechaVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(txtIdRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscadorEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPaternoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMaternoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadGarrafonesDevueltos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadGarrafonesSolicitados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtCantidadGarrafonesVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadGarrafones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularTotalGarrafones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarSubVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        jDialog2.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 900, 670));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 32, 32));

        txtIdVenta.setToolTipText("");
        jPanel1.add(txtIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 100, 32));

        txtNombreCliente.setEditable(false);
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 320, 30));

        txtPrecioEspecial.setEditable(false);
        jPanel1.add(txtPrecioEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 30));

        btnAgregar.setBackground(new java.awt.Color(38, 157, 46));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnAgregar.setText("Agregar venta.");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 160, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Datos productos.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        lblFechaVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(lblFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 80, 20));

        txtIdMayorista.setToolTipText("");
        jPanel1.add(txtIdMayorista, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 100, 32));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 32, 32));

        btnBuscadorClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscadorClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscador1.png"))); // NOI18N
        btnBuscadorClientes.setContentAreaFilled(false);
        btnBuscadorClientes.setOpaque(true);
        jPanel1.add(btnBuscadorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 30, 30));

        txtCambio.setText("Cambio");
        jPanel1.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 90, 30));

        btnCalcularTotal.setBackground(new java.awt.Color(38, 157, 46));
        btnCalcularTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCalcularTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularTotal.setText("Calcular cambio.");
        jPanel1.add(btnCalcularTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setText("Registro de venta.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Datos cliente.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 32, 32));

        txtIdEmpleado.setToolTipText("");
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 32));

        txtTotal.setText("Total");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 90, 30));

        tablaRegistroProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "Nombre", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaRegistroProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 390, 120));

        btnRepartidor.setBackground(new java.awt.Color(38, 157, 46));
        btnRepartidor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        btnRepartidor.setText("Repartidor.");
        jPanel1.add(btnRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 100, 40));

        btnProducto.setBackground(new java.awt.Color(38, 157, 46));
        btnProducto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setText("Productos.");
        jPanel1.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 100, 40));

        txtApellidoPaternoCliente.setEditable(false);
        jPanel1.add(txtApellidoPaternoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 680));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Ventas.");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdVenta", "Total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableVenta);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 590));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 490, 680));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btnSalir.setContentAreaFilled(false);
        btnSalir.setOpaque(true);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 24, 24));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirProductos2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirProductos2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirProductos2MouseEntered

    private void btnSalirProductos2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirProductos2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirProductos2MouseExited

    private void btnSalirProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirProductos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirProductos2ActionPerformed

    private void btnAgregarProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductosMouseEntered

    private void btnAgregarProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductosMouseExited

    private void btnAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProductosActionPerformed

    private void btnAgregarIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarIDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarIDMouseEntered

    private void btnAgregarIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarIDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarIDMouseExited

    private void btnAgregarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarIDActionPerformed

    private void txtCantidadGarrafonesVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadGarrafonesVendidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadGarrafonesVendidosActionPerformed

    private void cbPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPreciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPreciosActionPerformed

    private void txtTotalVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalVentaActionPerformed

    private void btnAgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarVentaActionPerformed

    private void btnCalcularTotalGarrafonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalGarrafonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularTotalGarrafonesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAgregarID;
    public javax.swing.JButton btnAgregarProductos;
    public javax.swing.JButton btnAgregarSubVentas;
    public javax.swing.JButton btnAgregarVenta;
    public javax.swing.JButton btnBuscadorClientes;
    public javax.swing.JButton btnBuscadorEmpleado;
    public javax.swing.JButton btnCalcularTotal;
    public javax.swing.JButton btnCalcularTotalGarrafones;
    public javax.swing.JButton btnProducto;
    public javax.swing.JButton btnRepartidor;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSalirProductos2;
    public javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cbPrecios;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JDialog jDialog2;
    public javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JLabel lblFechaVenta;
    public javax.swing.JLabel lblFechaVenta1;
    public javax.swing.JTable tablaMayoristas;
    public javax.swing.JTable tablaProductos2;
    public javax.swing.JTable tablaRegistroProductos;
    public javax.swing.JTable tablaRegistroProductosRepartidor;
    public javax.swing.JTable tableVenta;
    public javax.swing.JTextField txtApellidoMaternoRepartidor;
    public javax.swing.JTextField txtApellidoPaternoCliente;
    public javax.swing.JTextField txtApellidoPaternoRepartidor;
    public javax.swing.JTextField txtCambio;
    public javax.swing.JTextField txtCantidad2;
    public javax.swing.JTextField txtCantidadGarrafones;
    public javax.swing.JTextField txtCantidadGarrafonesDevueltos;
    public javax.swing.JTextField txtCantidadGarrafonesSolicitados;
    public javax.swing.JTextField txtCantidadGarrafonesVendidos;
    public javax.swing.JTextField txtIdEmpleado;
    public javax.swing.JTextField txtIdMayorista;
    public javax.swing.JTextField txtIdRepartidor;
    public javax.swing.JTextField txtIdVenta;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtNombreEmpleado;
    public javax.swing.JTextField txtPrecioEspecial;
    public javax.swing.JTextField txtTelefonoRepartidor;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
